### ISSUE TITLE
Problem with autospec

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#10]
Since you said on Issue 9 that it doesnot work with bundler, so installed it as a plugin and it works on development env.
But when I run my spec, the error shown below:

```
ActionView::TemplateError in 'CampaignsController index action should render index template'
undefined local variable or method `rightjs_scripts' for #<ActionView::Base:0x1193bb90>
On line #9 of app/views/layouts/application.html.haml

    6:       = h(yield(:title) || "Untitled")
    7:     %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    8:     = stylesheet_link_tag 'application'
    9:     = rightjs_scripts
    10:     = yield(:head)
    11:   
    12:   %body

    app/views/layouts/application.html.haml:9:in `_run_haml_app47views47layouts47application46html46haml'
    haml (2.2.20) lib/haml/helpers/action_view_mods.rb:13:in `render_without_mock_proxy'
    /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rspec-rails-1.3.2/lib/spec/rails/extensions/action_view/base.rb:27:in `render'
    haml (2.2.20) lib/haml/helpers/action_view_mods.rb:13:in `render_without_mock_proxy'
    /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rspec-rails-1.3.2/lib/spec/rails/extensions/action_view/base.rb:27:in `render'
    /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rspec-rails-1.3.2/lib/spec/rails/example/controller_example_group.rb:233:in `render'
    haml (2.2.20) rails/./lib/sass/plugin/rails.rb:20:in `process'
    spec/controllers/campaigns_controller_spec.rb:7
    rspec (1.3.0) lib/spec/example/example_methods.rb:40:in `instance_eval'
    rspec (1.3.0) lib/spec/example/example_methods.rb:40:in `execute'
    /home/millisami/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/timeout.rb:53:in `timeout'
    rspec (1.3.0) lib/spec/example/example_methods.rb:37:in `execute'
    rspec (1.3.0) lib/spec/example/example_group_methods.rb:214:in `run_examples'
    rspec (1.3.0) lib/spec/example/example_group_methods.rb:212:in `each'
    rspec (1.3.0) lib/spec/example/example_group_methods.rb:212:in `run_examples'
    rspec (1.3.0) lib/spec/example/example_group_methods.rb:103:in `run'
    rspec (1.3.0) lib/spec/runner/example_group_runner.rb:23:in `run'
    rspec (1.3.0) lib/spec/runner/example_group_runner.rb:22:in `each'
    rspec (1.3.0) lib/spec/runner/example_group_runner.rb:22:in `run'
    rspec (1.3.0) lib/spec/runner/options.rb:152:in `run_examples'
    rspec (1.3.0) lib/spec/runner/command_line.rb:9:in `run'
    rspec (1.3.0) bin/spec:5

Finished in 0.935905 seconds
```

I think it complains that rightjs_scripts because its not in the Gemfile.
Why is this behaviour??

**Comment by kaievns** [comment]
Seem like it doesn't load the RightRails helpers. Hard to say why.

As a temporary solution I'd suggest you load up them in your spec_helper, or you could play with the init.rb file and make it working. I honestly a bit busy with work and could use some help sorting those things out.

**Comment by millisami** [comment]
I tried with loading in spec_helper file, `require 'right_rails'`, but no luck.
I then even opened up the init.rb file, but couldn't made it working.

**Comment by kaievns** [comment]
I've just updated the gem to version 0.5.3, generator still missing, but specs are now working fine.

Plz, check it out

**Comment by millisami** [comment]
Yup, the specs are now running.
Thanks.
