### ISSUE TITLE
undefined method `link_to_remote_edit'

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#11]
- div_for vendor_board_type do
  The following is my my partial _vendor_board_type.html.haml
  
  %h3= h vendor_board_type.name
  %h4= h vendor_board_type.rate
  .actions
    = link_to_lightbox 'Show', vendor_board_type
    = link_to_remote_edit vendor_board_type

While rendering the partial in the index page at `http://localhost:3000/vendor_board_types`, I get the following error: The error is due to the `link_to_remote_edit` function.

Is it due to haml? coz the demo app has the same method working.

```
 NoMethodError in Vendor_board_types#index

Showing app/views/vendor_board_types/_vendor_board_type.html.haml where line #7 raised:

undefined method `link_to_remote_edit' for #<ActionView::Base:0xdd75ad4>

Extracted source (around line #7):

4:   .actions
5:     //= link_to 'Show', vendor_board_type
6:     = link_to_lightbox 'Show', vendor_board_type
7:     = link_to_remote_edit vendor_board_type
8:     //= link_to_remote_destroy vendor_board_type

Trace of template inclusion: app/views/vendor_board_types/index.html.haml

RAILS_ROOT: /home/millisami/rails_apps/automation
Application Trace | Framework Trace | Full Trace

/home/millisami/rails_apps/automation/app/views/vendor_board_types/_vendor_board_type.html.haml:7
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers.rb:322:in `call'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers.rb:322:in `capture_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers.rb:524:in `with_haml_buffer'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers.rb:318:in `capture_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers/action_view_mods.rb:88:in `capture'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/helpers/tag_helper.rb:70:in `content_tag_without_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers/action_view_mods.rb:108:in `content_tag'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/helpers/record_tag_helper.rb:54:in `content_tag_for'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/helpers/record_tag_helper.rb:16:in `div_for'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `send'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/base.rb:306:in `with_template'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable.rb:30:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable_partial.rb:20:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:26:in `benchmark'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:26:in `benchmark'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable_partial.rb:19:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/template.rb:205:in `render_template'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable_partial.rb:44:in `render_partial'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/partials.rb:221:in `render_partial_collection'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/partials.rb:216:in `map'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/partials.rb:216:in `render_partial_collection'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/partials.rb:195:in `render_partial'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/base.rb:276:in `render_without_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers/action_view_mods.rb:11:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers.rb:96:in `non_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers/action_view_mods.rb:11:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `send'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/base.rb:306:in `with_template'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/renderable.rb:30:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/template.rb:205:in `render_template'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/base.rb:265:in `render_without_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers/action_view_mods.rb:13:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/base.rb:348:in `_render_with_layout'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_view/base.rb:262:in `render_without_haml'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/haml/helpers/action_view_mods.rb:13:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:1250:in `render_for_file'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:945:in `render_without_benchmark'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:1326:in `default_render'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:1332:in `perform_action_without_filters'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/filters.rb:617:in `call_filters'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/flash.rb:146:in `perform_action'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `send'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `process_without_filters'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `sass_old_process'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/haml-2.2.20/lib/sass/plugin/rails.rb:20:in `process'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:391:in `process'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/base.rb:386:in `call'
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:437:in `call'
```

**Comment by kaievns** [comment]
`link_to_remote_edit` is not part of RightRails, it's a simple helper defined in the demo application itself, the same as `link_to_remote_destroy`

**Comment by millisami** [comment]
Oh, my bad. I thought that is the right-rails method.
Anyways, thanks a lot.
And I'm really enjoying using right-rails.

**Comment by kaievns** [comment]
no problem at all. glad you like it 8)
