### ISSUE TITLE
uninitialized constant RightRails::ControllerExtensions (NameError)

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#8]
Hi, 
I setup a rails 2.3.5 app and gem management is done via bundler with the instruction at http://gembundler.com/rails23.html.
Everything is working fine with other gems. 
Now I've specified to use right-rails in my Gemfile and now rake and script/generate commands throws the error:

```
[~/rails_apps/automation (campaign)⚡] ➔ script/generate right_rails
/home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant': uninitialized constant RightRails::ControllerExtensions (NameError)
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in `const_missing'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/right-rails-0.5.0/lib/../init.rb:8
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/right-rails-0.5.0/lib/right-rails.rb:11
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler/runtime.rb:48:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler/runtime.rb:48:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler/runtime.rb:43:in `each'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler/runtime.rb:43:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler/runtime.rb:42:in `each'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler/runtime.rb:42:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/bundler-0.9.18/lib/bundler.rb:83:in `require'
    from /home/millisami/rails_apps/automation/config/boot.rb:115:in `load_gems'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.5/lib/initializer.rb:164:in `process'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
    from /home/millisami/rails_apps/automation/config/environment.rb:9
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.5/lib/commands/generate.rb:1:in `require'
    from /home/millisami/.rvm/gems/ree-1.8.7-2010.01/gems/rails-2.3.5/lib/commands/generate.rb:1
    from script/generate:3:in `require'
    from script/generate:3
```

**Comment by kaievns** [comment]
Hey,

Sorry for the delay. Unfortunately RightRails generator doesn't work with Bundler yet. I'm going to add the support in the next major version, but for now to generate the scripts under Rails3 or Rails2 + Bundler, you'll need to generate them on a clean Rails 2 project and then copy them in place manually.

The next major version should be out in couple of weeks I think

**Comment by millisami** [comment]
Thanks. 
So, for now I was able to install as plugin and it worked.
